spring:
  rabbitmq:
    host: 192.168.30.130 # 你的虚拟机IP
    port: 5672 # 端口
    virtual-host: /lzc # 虚拟主机
    username: lzc # 用户名
    password: welcome1 # 密码
    listener:
      simple:
        prefetch: 1 # 每次只能获取一条消息，处理完成才能获取下一个消息
    connection-timeout: 1s # 设置MQ的连接超时时间
    template:
      retry:
        enabled: true # 开启超时重试机制
        initial-interval: 1000ms # 失败后的初始等待时间
        multiplier: 1 # 失败后下次的等待时长倍数，下次等待时长 = initial-interval * multiplier
        max-attempts: 3 # 最大重试次数
knife4j:
  enable: true
  openapi:
    title: mq接口文档
    description: "mq接口文档"
    email: lzc@qq.com
    concat: lzc
    url: https://www.lzc.cn
    version: v1.0.0
    group:
      default:
        group-name: default
        api-rule: package
        api-rule-resources:
          - com.lzc.mq.controller