jdbc.ip=192.168.30.130
jdbc.port=30600
jdbc.username=root
jdbc.password=welcome1

# jdbc:mysql://[host][:port]/[database]
jdbc.url=jdbc:mysql://${jdbc.ip}:${jdbc.port}/test

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://${jdbc.ip}:${jdbc.port}/test?useUnicode=true&characterEncoding=utf8
spring.datasource.username=${jdbc.username}
spring.datasource.password:${jdbc.password}
